eureka:
  client:
    fetchRegistry: false #由于服务本身就为注册中心，因此不需要注册自己，所有设置为false
    registerWithEureka: false #由于注册中心的职责就是维护服务实例，不需要去检索服务，所有设置为false
    service-url:
      defaultZone: http://localhost:9001/eureka #服务注册中心的配置内容，指定服务注册中心的位置
  instance:
    hostname: eureka-server-two
server:
  port: 9002
spring:
  application:
    name: eureka-server-two
